# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RicSliderViewControllerDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'RicSliderViewController’,:path => '..'
  # Pods for RicSliderViewControllerDemo

  target 'RicSliderViewControllerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RicSliderViewControllerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
